namespace OpenOsk.Core.Keys;

/// <summary>
/// Windows virtual-key codes. The numeric values match the Win32 <c>VK_*</c> constants so the
/// Windows host can pass them straight to <c>SendInput</c>; the core library never depends on Win32.
/// </summary>
public enum VirtualKey : ushort
{
    None = 0x00,
    Back = 0x08,
    Tab = 0x09,
    Clear = 0x0C,
    Return = 0x0D,
    Shift = 0x10,
    Control = 0x11,
    Menu = 0x12,
    Pause = 0x13,
    Capital = 0x14,
    Escape = 0x1B,
    Space = 0x20,
    Prior = 0x21,
    Next = 0x22,
    End = 0x23,
    Home = 0x24,
    Left = 0x25,
    Up = 0x26,
    Right = 0x27,
    Down = 0x28,
    Snapshot = 0x2C,
    Insert = 0x2D,
    Delete = 0x2E,
    D0 = 0x30,
    D1 = 0x31,
    D2 = 0x32,
    D3 = 0x33,
    D4 = 0x34,
    D5 = 0x35,
    D6 = 0x36,
    D7 = 0x37,
    D8 = 0x38,
    D9 = 0x39,
    A = 0x41,
    B = 0x42,
    C = 0x43,
    D = 0x44,
    E = 0x45,
    F = 0x46,
    G = 0x47,
    H = 0x48,
    I = 0x49,
    J = 0x4A,
    K = 0x4B,
    L = 0x4C,
    M = 0x4D,
    N = 0x4E,
    O = 0x4F,
    P = 0x50,
    Q = 0x51,
    R = 0x52,
    S = 0x53,
    T = 0x54,
    U = 0x55,
    V = 0x56,
    W = 0x57,
    X = 0x58,
    Y = 0x59,
    Z = 0x5A,
    LWin = 0x5B,
    RWin = 0x5C,
    Apps = 0x5D,
    NumPad0 = 0x60,
    NumPad1 = 0x61,
    NumPad2 = 0x62,
    NumPad3 = 0x63,
    NumPad4 = 0x64,
    NumPad5 = 0x65,
    NumPad6 = 0x66,
    NumPad7 = 0x67,
    NumPad8 = 0x68,
    NumPad9 = 0x69,
    Multiply = 0x6A,
    Add = 0x6B,
    Separator = 0x6C,
    Subtract = 0x6D,
    Decimal = 0x6E,
    Divide = 0x6F,
    F1 = 0x70,
    F2 = 0x71,
    F3 = 0x72,
    F4 = 0x73,
    F5 = 0x74,
    F6 = 0x75,
    F7 = 0x76,
    F8 = 0x77,
    F9 = 0x78,
    F10 = 0x79,
    F11 = 0x7A,
    F12 = 0x7B,
    NumLock = 0x90,
    Scroll = 0x91,
    LShift = 0xA0,
    RShift = 0xA1,
    LControl = 0xA2,
    RControl = 0xA3,
    LMenu = 0xA4,
    RMenu = 0xA5,
    BrowserBack = 0xA6,
    BrowserForward = 0xA7,
    VolumeMute = 0xAD,
    VolumeDown = 0xAE,
    VolumeUp = 0xAF,
    MediaNextTrack = 0xB0,
    MediaPrevTrack = 0xB1,
    MediaStop = 0xB2,
    MediaPlayPause = 0xB3,
    Oem1 = 0xBA,
    OemPlus = 0xBB,
    OemComma = 0xBC,
    OemMinus = 0xBD,
    OemPeriod = 0xBE,
    Oem2 = 0xBF,
    Oem3 = 0xC0,
    Oem4 = 0xDB,
    Oem5 = 0xDC,
    Oem6 = 0xDD,
    Oem7 = 0xDE,
    Oem8 = 0xDF,
    Oem102 = 0xE2,
}

public static class VirtualKeyInfo
{
    private static readonly HashSet<VirtualKey> ExtendedKeys =
    [
        VirtualKey.Insert,
        VirtualKey.Delete,
        VirtualKey.Home,
        VirtualKey.End,
        VirtualKey.Prior,
        VirtualKey.Next,
        VirtualKey.Left,
        VirtualKey.Up,
        VirtualKey.Right,
        VirtualKey.Down,
        VirtualKey.RControl,
        VirtualKey.RMenu,
        VirtualKey.LWin,
        VirtualKey.RWin,
        VirtualKey.Apps,
        VirtualKey.Divide,
        VirtualKey.NumLock,
        VirtualKey.Snapshot,
        VirtualKey.BrowserBack,
        VirtualKey.BrowserForward,
        VirtualKey.VolumeMute,
        VirtualKey.VolumeDown,
        VirtualKey.VolumeUp,
        VirtualKey.MediaNextTrack,
        VirtualKey.MediaPrevTrack,
        VirtualKey.MediaStop,
        VirtualKey.MediaPlayPause,
    ];

    /// <summary>
    /// True for keys that carry the 0xE0 scan-code prefix on a PC keyboard. These must be
    /// injected with the extended flag or Windows will treat them as their numpad twins.
    /// </summary>
    public static bool IsExtended(VirtualKey key) => ExtendedKeys.Contains(key);

    public static bool IsLetter(VirtualKey key) => key >= VirtualKey.A && key <= VirtualKey.Z;

    public static bool IsDigit(VirtualKey key) => key >= VirtualKey.D0 && key <= VirtualKey.D9;

    public static bool IsNumPad(VirtualKey key) => key >= VirtualKey.NumPad0 && key <= VirtualKey.Divide;

    /// <summary>
    /// What a numeric-pad key produces while Num Lock is off (NumPad7 → Home, Decimal → Delete, ...),
    /// or <see cref="VirtualKey.None"/> for keys Num Lock does not affect.
    /// </summary>
    public static VirtualKey NumLockOffKey(VirtualKey key) => key switch
    {
        VirtualKey.NumPad0 => VirtualKey.Insert,
        VirtualKey.NumPad1 => VirtualKey.End,
        VirtualKey.NumPad2 => VirtualKey.Down,
        VirtualKey.NumPad3 => VirtualKey.Next,
        VirtualKey.NumPad4 => VirtualKey.Left,
        VirtualKey.NumPad5 => VirtualKey.Clear,
        VirtualKey.NumPad6 => VirtualKey.Right,
        VirtualKey.NumPad7 => VirtualKey.Home,
        VirtualKey.NumPad8 => VirtualKey.Up,
        VirtualKey.NumPad9 => VirtualKey.Prior,
        VirtualKey.Decimal => VirtualKey.Delete,
        _ => VirtualKey.None,
    };
}
